app = "cfb-pickem-app"
primary_region = "ord"
console_command = "/bin/bash"

[build]

[deploy]
  strategy = "rolling"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[mounts]
  source = "cfb_data"
  destination = "/app/server/data"
  initial_size = "1gb"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"