[variables]
NODE_VERSION = "20"

[phases.install]
cmds = ["npm install", "cd client && npm install", "cd server && npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"