[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"

# Mount persistent volume for database storage
[[deploy.volumes]]
mountPath = "/data"
name = "cfb-database"

[variables]
NODE_VERSION = "20.19.0"